export const initialPlayers = [
  { id: 1,  name: 'Emon',         weight: 4 },
  { id: 2,  name: 'Kibria',       weight: 2 },
  { id: 3,  name: 'Shahed',       weight: 4 },
  { id: 4,  name: 'Rahat', weight: 2 },
  { id: 5,  name: 'Ashiq',        weight: 4 },
  { id: 6,  name: 'Rakib',        weight: 4 },
  { id: 7,  name: 'Abid',         weight: 3 },
  { id: 8,  name: 'Ashish',       weight: 3 },
  { id: 9,  name: 'Calvin',       weight: 3 },
  { id: 10, name: 'Shishir',      weight: 3 },
  { id: 11, name: 'Elias',        weight: 3 },
  { id: 12, name: 'Hasan',        weight: 3 },
  { id: 13, name: 'Rokon',        weight: 2 },
  { id: 14, name: 'Eshan',        weight: 2 },
  { id: 15, name: 'Mezanur',     weight: 2 },
  { id: 17, name: 'Emroz',        weight: 1 },
  { id: 18, name: 'Kamruzzaman',       weight: 2 },
  { id: 19, name: 'Rafiqul',      weight: 2 },
  { id: 20, name: 'Emon-Support',  weight: 2 },
  { id: 21, name: 'Evan',         weight: 3 },
  { id: 22, name: 'Samiul',       weight: 3 },
  { id: 23, name: 'Shahnewaz',    weight: 1 },
  { id: 24, name: 'Riaz',         weight: 2 },
];
