export const initialPlayers = [
//  { id: 1, name: 'Foysal', weight: 4 },
//   { id: 2, name: 'Mehrab', weight: 4 },
 // {id : 2, name: 'Samiul', weight:4 },
  { id: 3, name: 'Emon', weight: 4 },
  { id: 4, name: 'Nazmul', weight: 4 },
  { id: 5, name: 'Shahed', weight: 4 },
  { id: 6, name: 'Sakib-Laravel', weight: 4 },
  { id: 7, name: 'Ashiq', weight: 4 },
  { id: 8, name: 'Rakib', weight: 4 },
  { id: 9, name: 'Abid', weight: 3 },
  // { id: 10, name: 'Tofayel', weight: 3 },
  { id: 11, name: 'Ashish', weight: 3 },
  { id: 12, name: 'Calvin', weight: 3 },
  // { id: 13, name: 'Shehab', weight: 3 },
  { id: 14, name: 'Shofiqur', weight: 3 },
  { id: 15, name: 'Shishir', weight: 3 },
//   { id: 16, name: 'Imran', weight: 3 },
  { id: 17, name: 'Elias', weight: 3 },
  { id: 18, name: 'Akash', weight: 3 },
  { id: 19, name: 'Hasan', weight: 3 },
  { id: 20, name: 'Billal', weight: 2 },
  { id: 21, name: 'Rokon', weight: 2 },
  { id: 22, name: 'Eshan', weight: 2 },
  { id: 23, name: 'Sakib-UL', weight: 1 },
  { id: 24, name: 'Naim', weight: 2 },
//   { id: 25, name: 'Ahmed', weight: 2 },
  { id: 26, name: 'Emroz', weight: 1 },
  { id: 27, name: 'Rabiul', weight: 2 },
//  { id: 28, name: 'Sajidur', weight: 1 },
//  { id: 29, name: 'Sohel', weight: 1 },
  { id: 30, name: 'Prince', weight: 2 },
  { id: 31, name: 'Zitan', weight: 1 },
  { id: 32, name: 'Rasel', weight: 1 },
  { id: 33, name: 'Younoch', weight: 1 },
  { id: 34, name: 'Evan', weight: 2 },
  { id :35, name: 'Raihan', weight :1},
  {id:36, name : 'Shahnewaz', weight :1},
  {id:37, name : 'Tufyal', weight :2},
// {id:38, name: 'Rafiqul', weight:3},
 {id:39, name: 'Riaz', weight:2},

];
