export const initialPlayers = [
  { id: 1,  name: 'Emon',         weight: 4 },
  { id: 2,  name: 'Kibria',       weight: 2 },
  { id: 3,  name: 'Shahed',       weight: 4 },
  { id: 4,  name: 'Rahat',        weight: 2 },
  { id: 5,  name: 'Ashiq',        weight: 4 },
  { id: 6,  name: 'Rakib',        weight: 4 },
  { id: 7,  name: 'Calvin',       weight: 3 },
  { id: 8, name: 'Shishir',       weight: 3 },
  { id: 9, name: 'Elias',         weight: 3 },
  { id: 10, name: 'Hasan',        weight: 3 },
  { id: 11, name: 'Eshan',        weight: 2 },
  { id: 12, name: 'Mezanur',      weight: 2 },
  { id: 13, name: 'Emroz',        weight: 1 },
  { id: 14, name: 'Kamruzzaman',  weight: 2 },
  { id: 15, name: 'Emon-Support', weight: 2 },
  { id: 16, name: 'Evan',         weight: 3 },
  { id: 17, name: 'Shahnewaz',    weight: 1 },
  { id: 18, name: 'Riaz',         weight: 2 },
];
